### ISSUE TITLE
Error when installing locally 

### ISSUE THREAD

**Issue by brey** [oceanmodeling/searvey#4]
Trying `python -m pip install -e .` gives:

```
  ERROR: Command errored out with exit status 1:
   command: /Users/brey/miniconda3/envs/searvey/bin/python /Users/brey/miniconda3/envs/searvey/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/rz/63vzrg3547x1_d0z04_vrb_00000gn/T/tmpsva1lntj
       cwd: /Users/brey/GitHub/searvey
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/Users/brey/miniconda3/envs/searvey/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/brey/miniconda3/envs/searvey/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/brey/miniconda3/envs/searvey/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/private/var/folders/rz/63vzrg3547x1_d0z04_vrb_00000gn/T/pip-build-env-8dcboa1n/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
    File "/private/var/folders/rz/63vzrg3547x1_d0z04_vrb_00000gn/T/pip-build-env-8dcboa1n/overlay/lib/python3.9/site-packages/poetry/core/factory.py", line 43, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)

```

**Comment by pmav99** [comment]
this is because I used poetry 1.2 instead of poetry 1.1. I will fix it.
